plugins:
  - jekyll-youtube
  - jekyll-spaceship

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      permalink: /:path/:basename
      depth_order: 9999
  - scope:
      path: "README.md"
    values:
      permalink: /
      depth_order: 1

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude:
  - "*.iml"
  - ".idea/"

########################################

jekyll-spaceship:
  processors:
    - table-processor
    - media-processor