plugins:
  - jekyll-titles-from-headings

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      strip_title: true

collections:
  sections:
    output: true
    permalink: :path

titles_from_headings:
  enabled: true
  strip_title: false
  collections: true
