includes_dir: ""

collections:
  posts:
    output: false

plugins:
  - jekyll-spaceship

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      permalink: /:path/:basename
  - scope:
      path: "README.md"
    values:
      permalink: "/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude:
  - "*.iml"
  - ".idea/"
  - "_jekyll-potion"
  - "_exclude"

sass:
  style: compressed

########################################

jekyll-spaceship:
  processors:
    - table-processor
    - media-processor
    - mathjax-processor
    - polyfill-processor
  mathjax-processor:
    config:
      options:
        enableMenu: false

########################################

potion_config:
  theme: proto
  title: Developers | Guide
  is_make_title: true
  is_show_pagination: true
  is_show_empty_to_child_pages: true
########################################

########################################

potion:
  title: Developers | Guide
########################################

jekyll-potion:
  title: Developers | Guide
