plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-youtube

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "README.md"
    values:
      permalink: /
  - scope:
      path: "_sections/**/**"
    values:
      parent: true

collections:
  posts:
    output : false
  sections:
    output: true
    permalink: /:path

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

include:
  - README.md
exclude:
  - document.iml
  - .idea/**

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
